name = "dio"
uuid = "8016d6df-ef28-4dce-9347-78e67e45b845"
authors = ["thautwarm <twshere@outlook.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
